platform :ios, '8.0'

target 'HowMuch' do
  pod 'Parse', '~> 1.8.5'
  pod 'ParseTwitterUtils', '~> 1.8.5' 
  pod 'DKTwitterReverseAuth', '~> 0.1'
  pod 'Reachability', '~> 3.2'
  pod 'DKParseAuth', :path => '~/Documents/DKParseAuth'
end

target 'HowMuchTests' do

end

target 'HowMuchUITests' do

end

plugin 'cocoapods-keys', {
    :project => 'how-much',
    :keys => [
    'TwitterConsumerKey',
    'TwitterConsumerSecret',
    'ParseClientId',
    'ParseClientKey'
    ]
}
