platform :ios, '8.0'

target 'HowMuch' do
  pod 'Reachability', '~> 3.2'
  pod 'DKParseAuth'
end

target 'HowMuchTests' do

end

target 'HowMuchUITests' do

end

plugin 'cocoapods-keys', {
    :project => 'how-much',
    :keys => [
    'TwitterConsumerKey',
    'TwitterConsumerSecret',
    'ParseClientId',
    'ParseClientKey'
    ]
}
